### ISSUE TITLE
lots of "Type str doesn't support the buffer API" errors

### ISSUE THREAD

**Issue by polycopter** [akrylysov/yozuch#2]
e.g.:

D:\src\html>cd devblog

D:\src\html\devblog>yozuch serve
[   INFO] Loaded 1 posts
[   INFO] Loaded 1 documents
[   INFO] Processing assets directory D:\src\html\devblog\assets...
[   INFO] Processing assets directory C:\Python34\lib\site-packages\yozuch\theme
s\foundation\assets...
[   INFO] Found 1 tags
[   INFO] Writing content...
[   INFO] Done!
[   INFO] Watching D:\src\html\devblog\documents for changes...
[   INFO] Watching D:\src\html\devblog\posts for changes...
[   INFO] Watching D:\src\html\devblog\templates for changes...
[   INFO] Watching D:\src\html\devblog\assets for changes...
[   INFO] Watching config.py for changes...
[   INFO] Serving content at port 8000
[   INFO] Auto reload server at port 8001
[   INFO] Press "Ctrl+C" to exit
127.0.0.1 - - [06/Jan/2016 12:37:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [06/Jan/2016 12:37:00] "GET /css/foundation.min.css HTTP/1.1" 200
-
127.0.0.1 - - [06/Jan/2016 12:37:00] "GET /css/yozuch.css HTTP/1.1" 200 -
127.0.0.1 - - [06/Jan/2016 12:37:00] "GET /css/pygments.css HTTP/1.1" 200 -
127.0.0.1 - - [06/Jan/2016 12:37:01] code 404, message File not found
127.0.0.1 - - [06/Jan/2016 12:37:01] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [06/Jan/2016 12:37:01] code 404, message File not found
127.0.0.1 - - [06/Jan/2016 12:37:01] "GET /favicon.ico HTTP/1.1" 404 -
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python34\lib\site-packages\yozuch\notification_server.py", line 46, i
n _handle_client
    if self._handshake(client):
  File "C:\Python34\lib\site-packages\yozuch\notification_server.py", line 36, i
n _handshake
    headers = self._parse_headers(data)
  File "C:\Python34\lib\site-packages\yozuch\notification_server.py", line 28, i
n _parse_headers
    parts = line.split(': ', 2)
TypeError: Type str doesn't support the buffer API

127.0.0.1 - - [06/Jan/2016 12:37:10] "GET /blog/2016/01/06/demo-post/ HTTP/1.1"
200 -
127.0.0.1 - - [06/Jan/2016 12:37:10] "GET /css/foundation.min.css HTTP/1.1" 200
-
127.0.0.1 - - [06/Jan/2016 12:37:10] "GET /css/yozuch.css HTTP/1.1" 200 -
127.0.0.1 - - [06/Jan/2016 12:37:10] "GET /css/pygments.css HTTP/1.1" 200 -
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python34\lib\site-packages\yozuch\notification_server.py", line 46, i
n _handle_client
    if self._handshake(client):
  File "C:\Python34\lib\site-packages\yozuch\notification_server.py", line 36, i
n _handshake
    headers = self._parse_headers(data)
  File "C:\Python34\lib\site-packages\yozuch\notification_server.py", line 28, i
n _parse_headers
    parts = line.split(': ', 2)
TypeError: Type str doesn't support the buffer API

**Comment by akrylysov** [comment]
Thank you, the issue was fixed, going to upload the new version to PyPI on this week.

**Comment by akrylysov** [comment]
Just uploaded the new version to PyPi, run `pip install -U yozuch` to upgrade your package.
