### ISSUE TITLE
templates?

### ISSUE THREAD

**Issue by nobrowser** [akrylysov/yozuch#4]
Hi, I don't understand how to use the template directory.  I mean, I know about Jinja, but how are they actually connected to the posts?

**Comment by akrylysov** [comment]
Hi, you can override any built-in template using your projects's `templates` directory. E.g. if you want to override a template for `posts`, make a copy of https://github.com/akrylysov/yozuch/blob/master/yozuch/themes/foundation/templates/post.html, place it to your `templates` directory and modify `posts.html`.
