### ISSUE TITLE
Base URL

### ISSUE THREAD

**Issue by nobrowser** [akrylysov/yozuch#5]
The pages in the production output have 2 properties:
1. They use absolute links, and
2. They don't set the base URL in the meta tags.

This is a really unfortunate combination, because it means I can't serve the result from a place that isn't the website root.  Such as http://example.com/~myusername/ .

I'd prefer relative links in any case,  but I can live with absolute links provided the base URL is set.  What is the URL variable from  config.py used for, anyway?

**Comment by akrylysov** [comment]
> What is the URL variable from config.py used for, anyway?

It is used e.g. in Atom feed.

Here are 2 possible solutions:

- Modify urls in `ROUTES` variable in config.py:

```
ROUTES = (
    route('/~myusername/', 'blog-index'),
    route('/~myusername/blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/', 'posts'),
    # ...
)
```

- Add `base` tag to the base template. Create `base.html` in your project's template directory:

```
{% extends "!theme/base.html" %}

{% block head_meta %}
    {{ super() }}
    <base href="http://example.com/~myusername/" />
{% endblock %}
```

Let me know if it works for you.
